# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couchino}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Aaron Quint}]
  s.date = %q{2012-03-21}
  s.description = %q{couchino is a different way of writing apps for CouchDB. The structure is up to you.}
  s.email = %q{shoehn@web.de}
  s.executables = [%q{couchino}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "HISTORY",
    "LICENSE",
    "README.md",
    "Rakefile",
    "bin/couchino",
    "couchino.gemspec",
    "lib/couchino.rb",
    "lib/couchino/cli.rb",
    "lib/couchino/plugin.rb",
    "lib/couchino/plugins/coffeescript.rb",
    "lib/couchino/plugins/compass.rb",
    "lib/couchino/plugins/credentials.rb",
    "lib/couchino/plugins/haml.rb",
    "lib/couchino/plugins/jim.rb",
    "lib/couchino/plugins/macro.rb",
    "lib/couchino/plugins/mustache.rb",
    "lib/couchino/pusher.rb",
    "lib/couchino/templates/Jimfile",
    "lib/couchino/templates/config.js.erb",
    "lib/couchino/templates/couchapprc.erb",
    "lib/couchino/templates/css/screen.css",
    "lib/couchino/templates/db/views/by_type/map.js",
    "lib/couchino/templates/hooks/before_build.rb",
    "lib/couchino/templates/index.html.erb",
    "lib/couchino/templates/js/app.js",
    "lib/couchino/templates/js/vendor/jquery-1.7.1.js",
    "lib/couchino/templates/js/vendor/jquery.couch-0.11.js",
    "lib/couchino/templates/js/vendor/sammy-0.7.1.js",
    "lib/couchino/templates/js/vendor/sammy.couch-0.1.0.js",
    "lib/couchino/templates/js/vendor/sha1.js",
    "lib/couchino/templates/rewrites.js.erb",
    "test/helper.rb",
    "test/test_compass_plugin.rb",
    "test/test_couchino_cli.rb",
    "test/test_couchino_pusher.rb",
    "test/test_credentials_plugin.rb",
    "test/test_macro_plugin.rb",
    "test/testapp/.couchapprc",
    "test/testapp/Jimfile",
    "test/testapp/config.js",
    "test/testapp/css/app.css",
    "test/testapp/db/views/only_map/map.js",
    "test/testapp/db/views/recent/map.js",
    "test/testapp/db/views/recent/reduce.js",
    "test/testapp/hooks/before_build.rb",
    "test/testapp/hooks/before_push.rb",
    "test/testapp/index.html",
    "test/testapp/js/app.js",
    "test/testapp/js/default.js",
    "test/testapp/js/vendor/jquery-1.4.2.js",
    "test/testapp/js/vendor/json2.js",
    "test/testapp/js/vendor/sammy-0.5.4.js",
    "test/testapp/js/vendor/sammy.mustache-0.5.4.js",
    "test/testapp/rewrites.js",
    "test/testapp/templates/index.mustache"
  ]
  s.homepage = %q{http://github.com/shoehn/couchino}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Cappuccino on CouchApp}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_runtime_dependency(%q<typhoeus>, ["~> 0.2.4"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.0"])
      s.add_runtime_dependency(%q<jim>, ["~> 0.3.1"])
      s.add_runtime_dependency(%q<compass>, ["~> 0.11"])
      s.add_runtime_dependency(%q<mustache>, ["~> 0.99"])
      s.add_runtime_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_dependency(%q<typhoeus>, ["~> 0.2.4"])
      s.add_dependency(%q<thor>, ["~> 0.14.0"])
      s.add_dependency(%q<jim>, ["~> 0.3.1"])
      s.add_dependency(%q<compass>, ["~> 0.11"])
      s.add_dependency(%q<mustache>, ["~> 0.99"])
      s.add_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<mime-types>, ["~> 1.16"])
    s.add_dependency(%q<typhoeus>, ["~> 0.2.4"])
    s.add_dependency(%q<thor>, ["~> 0.14.0"])
    s.add_dependency(%q<jim>, ["~> 0.3.1"])
    s.add_dependency(%q<compass>, ["~> 0.11"])
    s.add_dependency(%q<mustache>, ["~> 0.99"])
    s.add_dependency(%q<coffee-script>, ["~> 2.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

